# Generated by Django 4.2.27 on 2026-01-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adress',
            new_name='Address',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('EMPLOYEE', 'Employee')], default='CUSTOMER', max_length=20),
        ),
    ]
